version: 2.3.{build}
skip_tags: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet --version

    dotnet restore ./OurPresence.Modeller.Core.sln
build:
  project: ./OurPresence.Modeller.Core.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
artifacts:
- path: '**/*.nupkg'
notifications:
- provider: Email
  to:
  - allan.nielsen@emydex.com
  - imathome@zoho.com
  subject: Modeller.Core build
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false