version: 2.0.{build}
skip_tags: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  disable_publish_on_pr: true
before_build:
- cmd: >-
    dotnet --version

    dotnet restore ./Modeller-tool.sln
build:
  project: ./modeller-tool.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
artifacts:
- path: '**/*.nupkg'
notifications:
- provider: Email
  to:
  - allan.nielsen@jbssa.com.au
  - imathome@zoho.com
  subject: Modeller build failed
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false